name: Deploy Supabase Functions - fetch-recently-listened

on:
  push:
    branches:
      - main
    paths:
      - supabase/functions/fetch-recently-listened/**
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      VITE_SUPABASE_REFERENCE_ID: ${{ secrets.VITE_SUPABASE_REFERENCE_ID }}

    steps:
      - uses: actions/checkout@v3

      - uses: supabase/setup-cli@v1
        with:
          version: latest

      - run: supabase functions deploy fetch-recently-listened --project-ref $VITE_SUPABASE_REFERENCE_ID --import-map supabase/functions/import_maps.json
